Description of derlgl
Home > Src > Level_0 > derlgl.m
derlgl
PURPOSE
DERLGL Spectral (Legendre Gauss Lobatto) derivative matrix
SYNOPSIS
function [d] = derlgl(x,np)
DESCRIPTION
DERLGL      Spectral (Legendre Gauss Lobatto) derivative matrix
    [d]=derlgl(x,np) returns the spectral Legendre Gauss Lobatto derivative
    matrix d at the np LGL nodes x (on [-1,1]). np-1 is the polynomial
    degree used. Legendre Gauss Lobatto (LGL) grid
 Input: x = array of LGL nodes on [-1,1] (computed by xwlgl)
        np = number of LGL nodes (=n+1, n=polynomial interpolation degree)
 Output: D = spectral derivative matrix: formula  (2.3.28), pag. 80 CHQZ2
 Reference: CHQZ2 = C. Canuto, M.Y. Hussaini, A. Quarteroni, T.A. Zang,
                    "Spectral Methods. Fundamentals in Single Domains"
                    Springer Verlag, Berlin Heidelberg New York, 2006.
CROSS-REFERENCE INFORMATION
This function calls:
pnleg PNLEG Evaluates Legendre polynomial of degree n at x
This function is called by:
nonperiodic_burgers NONPERIODIC_BURGERS Numerical solution of non periodic Burgers equation
lgl_eig LGL_EIG Computes eigenvalues of first/second order spectral derivative matrices: collocation/G-NI, LGL nodes, 1D monodomain
adr_1d ADR_1D Numerical solution of the 1D boundary value problem (1.2.52)-(1.2.53), pag. 17, CHQZ2
ell_1d ELL_1D Numerical solution of the 1D elliptic boundary value problem (4.3.17) pag. 208, CHQZ2
ellprecofem_1d ELLPRECOFEM_1D FEM-preconditioned SEM-appx of 1D second order b.v.p.
lap_1d LAP_1D SEM appx of the 1D b.v.p. -nu u''+gam u=f
eig_schur_2d EIG_SCHUR_2D Eigenvalues computation Schur complement matrix
schur_2d SCHUR_2D Numerical solution of the 2D b.v.p. -Delta u + gam u -Schur complement
eig_schwarz_2d EIG_SCHWARZ_2D Eigenvalues computation for the matrix associated to 2D b.v.p. -Delta u + gam u = f + Dirichlet b.c.
schwarz_2d SCHWARZ_2D Numerical solution of the 2D boundary value problem
lap_2d LAP_2D Numerical solution of the 2D b.v.p. -Delta u + gam u = f
lap_3d LAP_3D Numerical solution of the 3D b.v.p. -Delta u + gam u = f
scalar_hyp SCALAR_HYP Numerical solution of scalar linear hyperbolic equations,
stag_scalar_hyp STAG_SCALAR_HYP Numerical solution of scalar linear hyperbolic equations,
stat_scalar_hyp STAT_SCALAR_HYP Numerical solution of a stationary scalar linear hyperbolic equation,
test TEST Script for testing functions of this directory
errors_1d ERRORS_1D Computes errors for 1D b.v.p.
matrices_1d MATRICES_1D Assembles SEM stiffness and mass matrices for 1D b.v.p.
SOURCE CODE
function [d] = derlgl(x,np)
%DERLGL      Spectral (Legendre Gauss Lobatto) derivative matrix
%
%    [d]=derlgl(x,np) returns the spectral Legendre Gauss Lobatto derivative
%    matrix d at the np LGL nodes x (on [-1,1]). np-1 is the polynomial
%    degree used. Legendre Gauss Lobatto (LGL) grid
%
%
% Input: x = array of LGL nodes on [-1,1] (computed by xwlgl)
%        np = number of LGL nodes (=n+1, n=polynomial interpolation degree)
%
% Output: D = spectral derivative matrix: formula  (2.3.28), pag. 80 CHQZ2
%
% Reference: CHQZ2 = C. Canuto, M.Y. Hussaini, A. Quarteroni, T.A. Zang,
%                    "Spectral Methods. Fundamentals in Single Domains"
%                    Springer Verlag, Berlin Heidelberg New York, 2006.
%   Written by Paola Gervasio
%   $Date: 2007/04/01$
d=zeros(np);
n=np-1;
for j =1:np
   lnxj = pnleg(x(j),n);
   for i = 1:np
      if i ~= j
         lnxi = pnleg(x(i),n);
         d(i,j) = lnxi/((x(i)-x(j))*lnxj);
      end
   end
end
d(1,1) = -0.25*n*np;
d(np,np) = -d (1,1);
return