Description of plot_sem_1d
Home > Src > Level_1 > plot_sem_1d.m
plot_sem_1d
PURPOSE
PLOT_SEM_1D plots SEM numerical solution of 1D boundary value problems
SYNOPSIS
function [ha]=plot_sem_1d(fig,ne,x,wx,xx,jacx,xy,nov,un,n_int);
DESCRIPTION
 PLOT_SEM_1D plots SEM numerical solution of 1D boundary value problems
   [ha]=plot_sem_1d(fig,ne,x,wx,xx,jacx,xy,nov,un,param);
 Input: fig =  figure number, set in the calling function by figure
                command
        ne = number of Spectral elements
        x = LGL nodes in [-1,1]
        wx= LGL weights in [-1,1]
        xx = 2-indexes array of size (2,ne): xx(1:2,ie)=[xa_ie;xb_ie]
        jacx= array (length(jacx)=ne); jacx(ie)= jacobian of
                of the map F_ie:[-1,1]---->[xa_ie,xb_ie]
        xy = column array with global mesh, length: noe=nov(npdx,ne)
        nov = local -global map, previously generated by cosnov1d
        un = numerical solution
        n_int = number of nodes in each element to interpolate numerical
        solution by Level_0/legendre_tr_eval.m (Discrete Legendre Transform)
CROSS-REFERENCE INFORMATION
This function calls:
legendre_tr_eval LEGENDRE_TR_EVAL Evaluates Discrete Legendre Transform
xwlgl XWLGL Computes nodes and weights of the Legendre-Gauss-Lobatto quadrature formula.
This function is called by:
adr_1d ADR_1D Numerical solution of the 1D boundary value problem (1.2.52)-(1.2.53), pag. 17, CHQZ2
lap_1d LAP_1D SEM appx of the 1D b.v.p. -nu u''+gam u=f
SOURCE CODE
function [ha]=plot_sem_1d(fig,ne,x,wx,xx,jacx,xy,nov,un,n_int);
% PLOT_SEM_1D plots SEM numerical solution of 1D boundary value problems
%
%   [ha]=plot_sem_1d(fig,ne,x,wx,xx,jacx,xy,nov,un,param);
%
% Input: fig =  figure number, set in the calling function by figure
%                command
%        ne = number of Spectral elements
%        x = LGL nodes in [-1,1]
%        wx= LGL weights in [-1,1]
%        xx = 2-indexes array of size (2,ne): xx(1:2,ie)=[xa_ie;xb_ie]
%        jacx= array (length(jacx)=ne); jacx(ie)= jacobian of
%                of the map F_ie:[-1,1]---->[xa_ie,xb_ie]
%        xy = column array with global mesh, length: noe=nov(npdx,ne)
%        nov = local -global map, previously generated by cosnov1d
%        un = numerical solution
%        n_int = number of nodes in each element to interpolate numerical
%        solution by Level_0/legendre_tr_eval.m (Discrete Legendre Transform)
%
%   Written by Paola Gervasio
%   $Date: 2007/04/01$
npdx=length(x);
u_int=zeros(n_int,ne);
plot(xy,un,'kx'); hold
%   interpolation
for ie=1:ne
x1=xwlgl(n_int);
uloc=un(nov(1:npdx,ie));
u_int(1:n_int,ie)=legendre_tr_eval(x,uloc,x1);
x1_jac=jacx(ie)*x1+0.5*(xx(2,ie)+xx(1,ie));
plot(x1_jac,u_int(1:n_int,ie));
end
ha=gca(fig);
hold off
return