Description of pol_legendre
Home > Src > Basis_functions > pol_legendre.m
pol_legendre
PURPOSE
POL_LEGENDRE recursive construction of Legendre basis function
SYNOPSIS
function [lnp1]=pol_legendre(n,ln,lnm1)
DESCRIPTION
 POL_LEGENDRE  recursive construction of Legendre basis function
            formula (2.3.19), pag. 77, CHQZ2
   [lnp1]=pol_legendre(n,ln,lnm1)
            called by plot_legendre
 Input: n = polynomial degree
        ln = character expression of L_n(x)
        lnm1 = character expression of L_{n-1}(x)
 Output: lnp1 = character expression of L_{n+1}(x)
 Reference: CHQZ2 = C. Canuto, M.Y. Hussaini, A. Quarteroni, T.A. Zang,
                    "Spectral Methods. Fundamentals in Single Domains"
                    Springer Verlag, Berlin Heidelberg New York, 2006.
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
plot_2dmodal PLOT_2DMODAL plots 2D modal boundary adapted polynomials.
plot_legendre PLOT_LEGENDRE plots 1D Legendre polynomials.
plot_modal PLOT_MODAL plots 1D modal boundary-adapted polynomials
SOURCE CODE
function [lnp1]=pol_legendre(n,ln,lnm1)
% POL_LEGENDRE  recursive construction of Legendre basis function
%            formula (2.3.19), pag. 77, CHQZ2
%   [lnp1]=pol_legendre(n,ln,lnm1)
%            called by plot_legendre
%
% Input: n = polynomial degree
%        ln = character expression of L_n(x)
%        lnm1 = character expression of L_{n-1}(x)
%
% Output: lnp1 = character expression of L_{n+1}(x)
%
% Reference: CHQZ2 = C. Canuto, M.Y. Hussaini, A. Quarteroni, T.A. Zang,
%                    "Spectral Methods. Fundamentals in Single Domains"
%                    Springer Verlag, Berlin Heidelberg New York, 2006.
%   Written by Paola Gervasio
%   $Date: 2007/04/01$
ns=num2str(n);
lnp1=['(2*',ns,'+1)/(',ns,'+1).*x.*(',ln,')-',ns,'/(',ns,'+1).*(',lnm1,')'];
return