Description of liste1
Home > Src > Level_2 > liste1.m
liste1
PURPOSE
LISTE1 Assembles lists of internal, boundary, interface nodes (similar to liste)
SYNOPSIS
function [lbor,lint,lintint,lgamma]=liste1(ifro);
DESCRIPTION
 LISTE1 Assembles lists of internal, boundary, interface nodes (similar to liste)
 [lbor,lint,lintint,lgamma]=liste1(ifro);
 It computes lists of internal, boundary, interface nodes.
 All lists are referred to global ordering on Omega
 Input : ifro = column array of length noe=nov(npdx*npdy,ne):
            if (x_i,y_i) is internal to Omega then ifro(i)=0,
            if (x_i,y_i) is on \partial\Omega then ifro(i)=1,
 Output:
 lbor: list of boundary nodes
 lint: list of internal nodes
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
eig_schur_2d EIG_SCHUR_2D Eigenvalues computation Schur complement matrix
schur_loc SCHUR_LOC Computes local matrices and lists for implementing the Schur method
schur_matrix SCHUR_MATRIX Computes Schur complement matrix Sigma and its preconditioner
stiffq1H STIFFQ1H Construction of stiffness Q1 matrix on the coarse grid.
SOURCE CODE
function [lbor,lint,lintint,lgamma]=liste1(ifro);
% LISTE1 Assembles lists of internal, boundary, interface nodes (similar to liste)
%
% [lbor,lint,lintint,lgamma]=liste1(ifro);
%
% It computes lists of internal, boundary, interface nodes.
% All lists are referred to global ordering on Omega
%
% Input : ifro = column array of length noe=nov(npdx*npdy,ne):
%            if (x_i,y_i) is internal to Omega then ifro(i)=0,
%            if (x_i,y_i) is on \partial\Omega then ifro(i)=1,
%
% Output:
% lbor: list of boundary nodes
% lint: list of internal nodes
%
%   Written by Paola Gervasio
%   $Date: 2007/04/01$
noe=length(ifro);
lint=[];lbor=[];lgamma=[]; lintint=[];
for i=1:noe
if(ifro(i)==1)
lbor=[lbor;i];
else
lint=[lint;i];
end
end
for i=1:length(lint)
if(ifro(i)==-1)
lgamma=[lgamma;i];
else
lintint=[lintint;i];
end
end
return