Description of derlg
Home > Src > Level_0 > derlg.m
derlg
PURPOSE
DERLG Spectral (Legendre Gauss) derivative matrix
SYNOPSIS
function [d] = derlg(x,np)
DESCRIPTION
DERLG      Spectral (Legendre Gauss) derivative matrix
    [d]=derlg(x,np) returns the spectral Legendre Gauss derivative
    matrix d at the np LG nodes X (in (-1,1)). np-1 is the polynomial
    degree used. Legendre Gauss (LG) grid
 Input: x = array of LG nodes on (-1,1) (computed by xwlg)
        np = number of LG nodes (=n+1, n=polynomial interpolation degree)
 Output: d = spectral derivative matrix
 Reference: CHQZ2 = C. Canuto, M.Y. Hussaini, A. Quarteroni, T.A. Zang,
                    "Spectral Methods. Fundamentals in Single Domains"
                    Springer Verlag, Berlin Heidelberg New York, 2006.
CROSS-REFERENCE INFORMATION
This function calls:
jacobi_eval JACOBI_EVAL: Evaluates Jacobi polynomial P_n^{(\alpha,\beta)} at x\in(-1,1)
This function is called by:
stag_scalar_hyp STAG_SCALAR_HYP Numerical solution of scalar linear hyperbolic equations,
test TEST Script for testing functions of this directory
SOURCE CODE
function [d] = derlg(x,np)
%DERLG      Spectral (Legendre Gauss) derivative matrix
%
%    [d]=derlg(x,np) returns the spectral Legendre Gauss derivative
%    matrix d at the np LG nodes X (in (-1,1)). np-1 is the polynomial
%    degree used. Legendre Gauss (LG) grid
%
%
% Input: x = array of LG nodes on (-1,1) (computed by xwlg)
%        np = number of LG nodes (=n+1, n=polynomial interpolation degree)
%
% Output: d = spectral derivative matrix
%
% Reference: CHQZ2 = C. Canuto, M.Y. Hussaini, A. Quarteroni, T.A. Zang,
%                    "Spectral Methods. Fundamentals in Single Domains"
%                    Springer Verlag, Berlin Heidelberg New York, 2006.
%   Written by Paola Gervasio
%   $Date: 2007/04/01$
n=np-1;
d=zeros(np);
 [p,pd] = jacobi_eval(x,np,0,0);
for i=1:np
for j=1:np
if(i~=j)
    d(i,j)=pd(i,1)/(pd(j,1)*(x(i)-x(j)));
elseif(i==j)
d(i,j)=x(i)/(1-x(i)*x(i));
end
end
end
return