Description of legendre_tr_eval
Home > Src > Level_0 > legendre_tr_eval.m
legendre_tr_eval
PURPOSE
LEGENDRE_TR_EVAL Evaluates Discrete Legendre Transform
SYNOPSIS
function [u_int]=legendre_tr_eval(x,u,x_int);
DESCRIPTION
 LEGENDRE_TR_EVAL     Evaluates Discrete Legendre Transform
            formula (4.4.17)  pag. 118, Quarteroni-Valli, Springer 1997
            with coefficients computed with formula (4.4.18)
                   pag. 118, Quarteroni-Valli, Springer 1997
  [u_int]=legendre_tr_eval(x,u,x_int) returns the evaluation at nodes x_int
       of the expansion of (I_N u)(x) with respect to Legendre polynomials
       (I_n u)(x)=\Sum_{k=0}^n u_k L_k(x)             (*)
       where L_k(x) are the Legendre polynomials
 Input: x = array of np Legendre Gauss Lobatto (LGL) nodes on [-1,1]
        u = array of np values of u at LGL nodes x : u_j=u(x_j)
            size(u)=[np,nc], where nc is the number of transforms which
            should be computed.
        If u is a 2-indices array, then every column of u is transformed
        following formula (*)
        x_int = array of a second set of nodes in [-1,1]
 Output: u_int = array of the values of  the
              expansion of I_Nu(x) with respect to Legendre polynomials.
 Reference: A. Quarteroni, A. Valli:
            "Numerical Approximation of Partial Differential Equations"
            Springer Verlag / 1997 (2nd Ed)
CROSS-REFERENCE INFORMATION
This function calls:
legendre_tr_coef LEGENDRE_TR_COEF Computes Discrete Legendre Transform coefficients
pnleg_all PNLEG_ALL Evaluates Legendre polynomials, from degree 0 to n
This function is called by:
call_ell_1d CALL_ELL_1D Script to produce results of fig. 4.17, pag. 207, CHQZ2
test TEST Script for testing functions of this directory
plot_sem_1d PLOT_SEM_1D plots SEM numerical solution of 1D boundary value problems
plot_sem_2d PLOT_SEM_2D Plots SEM numerical solution of 2D boundary value problems
SOURCE CODE
function [u_int]=legendre_tr_eval(x,u,x_int);
% LEGENDRE_TR_EVAL     Evaluates Discrete Legendre Transform
%
%            formula (4.4.17)  pag. 118, Quarteroni-Valli, Springer 1997
%            with coefficients computed with formula (4.4.18)
%                   pag. 118, Quarteroni-Valli, Springer 1997
%
%  [u_int]=legendre_tr_eval(x,u,x_int) returns the evaluation at nodes x_int
%       of the expansion of (I_N u)(x) with respect to Legendre polynomials
%
%       (I_n u)(x)=\Sum_{k=0}^n u_k L_k(x)             (*)
%
%       where L_k(x) are the Legendre polynomials
%
% Input: x = array of np Legendre Gauss Lobatto (LGL) nodes on [-1,1]
%        u = array of np values of u at LGL nodes x : u_j=u(x_j)
%            size(u)=[np,nc], where nc is the number of transforms which
%            should be computed.
%        If u is a 2-indices array, then every column of u is transformed
%        following formula (*)
%        x_int = array of a second set of nodes in [-1,1]
%
% Output: u_int = array of the values of  the
%              expansion of I_Nu(x) with respect to Legendre polynomials.
%
% Reference: A. Quarteroni, A. Valli:
%            "Numerical Approximation of Partial Differential Equations"
%            Springer Verlag / 1997 (2nd Ed)
%
%   Written by Paola Gervasio
%   $Date: 2007/04/01$
n1=length(x_int);
np=length(x); n=np-1;
uk=legendre_tr_coef(x,u);
pn=pnleg_all(x_int,n);
u_int=pn*uk;
return