Description of xwlg
Home > Src > Level_0 > xwlg.m
xwlg
PURPOSE
XWLG Computes nodes and weights of the Legendre-Gauss quadrature formula.
SYNOPSIS
function [x,w] = xwlg(np,a,b)
DESCRIPTION
XWLG  Computes nodes and weights of the Legendre-Gauss  quadrature formula.
    [x,w]=xwlg(np) returns the np weigths and nodes
    of the corresponding Legendre Gauss quadrature
    formula in the reference interval (-1,1).
    [x,w]=xwlg(np,a,b) returns the np weigths and the nodes
    of the corresponding Legendre Gauss quadrature
    formula in the  interval (a,b).
 Input: np = number of nodes
        a, b = extrema of the interval
 Output: x(np,1) = LG nodes  (CHQZ2, (2.3.10), pag. 76)
         w(np,1) = LG weigths (CHQZ2, (2.3.10), pag. 76)
 Reference: CHQZ2 = C. Canuto, M.Y. Hussaini, A. Quarteroni, T.A. Zang,
                    "Spectral Methods. Fundamentals in Single Domains"
                    Springer Verlag, Berlin Heidelberg New York, 2006.
CROSS-REFERENCE INFORMATION
This function calls:
jacobi_roots JACOBI_ROOTS: Computes the n zeros of the Jacoby polynomial P_n^{(\alpha,\beta)}(x)
pnleg1 PNLEG1 Evaluates the first derivative of Legendre polynomial
This function is called by:
stag_scalar_hyp STAG_SCALAR_HYP Numerical solution of scalar linear hyperbolic equations,
test TEST Script for testing functions of this directory
normah1_1d NORMAH1_1D Computes H1-norm in 1D
normal2_1d NORMAL2_1D Computes L2-norm in 1D
normah1_2d NORMAH1_2D Computes H1-norm in 2D
normal2_2d NORMAL2_2D Computes L2-norm in 2D
normah1_3d NORMAH1_3D Computes H1-norm in 3D
normal2_3d % NORMAL2_3D Computes L2-norm in 3D
SOURCE CODE
function [x,w] = xwlg(np,a,b)
%XWLG  Computes nodes and weights of the Legendre-Gauss  quadrature formula.
%
%    [x,w]=xwlg(np) returns the np weigths and nodes
%    of the corresponding Legendre Gauss quadrature
%    formula in the reference interval (-1,1).
%
%    [x,w]=xwlg(np,a,b) returns the np weigths and the nodes
%    of the corresponding Legendre Gauss quadrature
%    formula in the  interval (a,b).
%
% Input: np = number of nodes
%        a, b = extrema of the interval
%
% Output: x(np,1) = LG nodes  (CHQZ2, (2.3.10), pag. 76)
%         w(np,1) = LG weigths (CHQZ2, (2.3.10), pag. 76)
%
%
% Reference: CHQZ2 = C. Canuto, M.Y. Hussaini, A. Quarteroni, T.A. Zang,
%                    "Spectral Methods. Fundamentals in Single Domains"
%                    Springer Verlag, Berlin Heidelberg New York, 2006.
%   Written by Paola Gervasio
%   $Date: 2007/04/01$
n=np-1;
if np<=1
  x=0;w=2;
  return
end
x=jacobi_roots(np,0,0);
w=2./(pnleg1(x,np).^2.*(1-x.^2));
%
% map on (a,b)
%
if nargin == 3
  bma=(b-a)*.5;
  bpa=(b+a)*.5;
  x=bma*x+bpa;
  w=w*bma;
end
return