Description of xwlgl
Home > Src > Level_0 > xwlgl.m
xwlgl
PURPOSE
XWLGL Computes nodes and weights of the Legendre-Gauss-Lobatto quadrature formula.
SYNOPSIS
function [x,w] = xwlgl(np,a,b)
DESCRIPTION
XWLGL Computes nodes and weights of the Legendre-Gauss-Lobatto quadrature formula.
    [x,w]=xwlgl(np) returns the np weigths and nodes
    of the corresponding Legendre Gauss-Lobatto quadrature
    formula in the reference interval [-1,1].
    [x,w]=xwlgl(np,a,b) returns the np weigths and the nodes
    of the corresponding Legendre Gauss-Lobatto quadrature
    formula in the  interval [a,b].
 Input: np = number of nodes
        a, b = extrema of the interval
 Output: x(np,1) = LGL nodes  (CHQZ2, (2.3.12), pag. 76)
                   the set is given by (CHQZ2, pag. 92) as well:
               {-1} U {zeros of Jacobi polynomial P_{N-1}^{(1,1)}} U {1}
         w(np,1) = LGL weigths (CHQZ2, (2.3.12), pag. 76)
 Reference: CHQZ2 = C. Canuto, M.Y. Hussaini, A. Quarteroni, T.A. Zang,
                    "Spectral Methods. Fundamentals in Single Domains"
                    Springer Verlag, Berlin Heidelberg New York, 2006.
CROSS-REFERENCE INFORMATION
This function calls:
jacobi_roots JACOBI_ROOTS: Computes the n zeros of the Jacoby polynomial P_n^{(\alpha,\beta)}(x)
pnleg PNLEG Evaluates Legendre polynomial of degree n at x
This function is called by:
plot_2dlagrange PLOT_2DLAGRANGE plots 2D Lagrange polynomials.
plot_lagrange PLOT_LAGRANGE plots 1D Lagrange polynomials.
nonperiodic_burgers NONPERIODIC_BURGERS Numerical solution of non periodic Burgers equation
lgl_eig LGL_EIG Computes eigenvalues of first/second order spectral derivative matrices: collocation/G-NI, LGL nodes, 1D monodomain
adr_1d ADR_1D Numerical solution of the 1D boundary value problem (1.2.52)-(1.2.53), pag. 17, CHQZ2
call_ell_1d CALL_ELL_1D Script to produce results of fig. 4.17, pag. 207, CHQZ2
ell_1d ELL_1D Numerical solution of the 1D elliptic boundary value problem (4.3.17) pag. 208, CHQZ2
ellprecofem_1d ELLPRECOFEM_1D FEM-preconditioned SEM-appx of 1D second order b.v.p.
lap_1d LAP_1D SEM appx of the 1D b.v.p. -nu u''+gam u=f
eig_schur_2d EIG_SCHUR_2D Eigenvalues computation Schur complement matrix
schur_2d SCHUR_2D Numerical solution of the 2D b.v.p. -Delta u + gam u -Schur complement
eig_schwarz_2d EIG_SCHWARZ_2D Eigenvalues computation for the matrix associated to 2D b.v.p. -Delta u + gam u = f + Dirichlet b.c.
matr0t MATR0T Constructs matrix R_H^T used in (6.3.21), pag. 373 CHQZ3
schwarz_2d SCHWARZ_2D Numerical solution of the 2D boundary value problem
lap_2d LAP_2D Numerical solution of the 2D b.v.p. -Delta u + gam u = f
plot_mesh PLOT_MESH Script for plotting SEM mesh on a rectangle
lap_3d LAP_3D Numerical solution of the 3D b.v.p. -Delta u + gam u = f
scalar_hyp SCALAR_HYP Numerical solution of scalar linear hyperbolic equations,
stag_scalar_hyp STAG_SCALAR_HYP Numerical solution of scalar linear hyperbolic equations,
stat_scalar_hyp STAT_SCALAR_HYP Numerical solution of a stationary scalar linear hyperbolic equation,
test TEST Script for testing functions of this directory
errors_1d ERRORS_1D Computes errors for 1D b.v.p.
matrices_1d MATRICES_1D Assembles SEM stiffness and mass matrices for 1D b.v.p.
plot_sem_1d PLOT_SEM_1D plots SEM numerical solution of 1D boundary value problems
plot_sem_2d PLOT_SEM_2D Plots SEM numerical solution of 2D boundary value problems
SOURCE CODE
function [x,w] = xwlgl(np,a,b)
%XWLGL Computes nodes and weights of the Legendre-Gauss-Lobatto quadrature formula.
%
%    [x,w]=xwlgl(np) returns the np weigths and nodes
%    of the corresponding Legendre Gauss-Lobatto quadrature
%    formula in the reference interval [-1,1].
%
%    [x,w]=xwlgl(np,a,b) returns the np weigths and the nodes
%    of the corresponding Legendre Gauss-Lobatto quadrature
%    formula in the  interval [a,b].
%
% Input: np = number of nodes
%        a, b = extrema of the interval
%
% Output: x(np,1) = LGL nodes  (CHQZ2, (2.3.12), pag. 76)
%                   the set is given by (CHQZ2, pag. 92) as well:
%               {-1} U {zeros of Jacobi polynomial P_{N-1}^{(1,1)}} U {1}
%         w(np,1) = LGL weigths (CHQZ2, (2.3.12), pag. 76)
%
% Reference: CHQZ2 = C. Canuto, M.Y. Hussaini, A. Quarteroni, T.A. Zang,
%                    "Spectral Methods. Fundamentals in Single Domains"
%                    Springer Verlag, Berlin Heidelberg New York, 2006.
%   Written by Paola Gervasio
%   $Date: 2007/04/01$
if np <= 1
  es='The number of the quadrature nodes should be greater than 1';
  disp(es); x = []; w = [];
  return
elseif np==2
    x=[-1;1];w=[1;1];
else
x=zeros(np,1);
w=zeros(np,1);
n=np-1;
x(1)=-1;x(np)=1;
x1=jacobi_roots(n-1,1,1);
x(2:n)=x1;
coef=2/(n*np);
w=coef./(pnleg(x,n).^2);
end
if nargin ==3
   bma=(b-a)*.5;
   bpa=(b+a)*.5;
   x=bma*x+bpa;
   w=w*bma;
end
return