Description of cosnov_1d
Home > Src > Level_1 > cosnov_1d.m
cosnov_1d
PURPOSE
COSNOV_1D : Constructs the 1D (local mesh ---> global mesh) map
SYNOPSIS
function [nov]=cosnov_1d(npdx,ne,nov);
DESCRIPTION
 COSNOV_1D : Constructs the 1D (local mesh ---> global mesh) map
 [nov]=cosnov_1d(npdx,ne,nov) computes the 2-indeces array nov:
       nov(i,ie) = is the index, with respect to global numbering,
                   associated to node i of element ie.
 Input: npdx = number of nodes in one element (the same in every element)
        ne   = number of elements
        nov  = zeros(max(npdx),ne)
 Output: nov = 2-indeces array of local to global map.
 Reference: CHQZ2 = C. Canuto, M.Y. Hussaini, A. Quarteroni, T.A. Zang,
                    "Spectral Methods. Fundamentals in Single Domains"
                    Springer Verlag, Berlin Heidelberg New York, 2006.
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
adr_1d ADR_1D Numerical solution of the 1D boundary value problem (1.2.52)-(1.2.53), pag. 17, CHQZ2
ell_1d ELL_1D Numerical solution of the 1D elliptic boundary value problem (4.3.17) pag. 208, CHQZ2
ellprecofem_1d ELLPRECOFEM_1D FEM-preconditioned SEM-appx of 1D second order b.v.p.
lap_1d LAP_1D SEM appx of the 1D b.v.p. -nu u''+gam u=f
errors_1d ERRORS_1D Computes errors for 1D b.v.p.
SOURCE CODE
function [nov]=cosnov_1d(npdx,ne,nov);
% COSNOV_1D : Constructs the 1D (local mesh ---> global mesh) map
%
% [nov]=cosnov_1d(npdx,ne,nov) computes the 2-indeces array nov:
%       nov(i,ie) = is the index, with respect to global numbering,
%                   associated to node i of element ie.
%
% Input: npdx = number of nodes in one element (the same in every element)
%        ne   = number of elements
%        nov  = zeros(max(npdx),ne)
% Output: nov = 2-indeces array of local to global map.
%
%
% Reference: CHQZ2 = C. Canuto, M.Y. Hussaini, A. Quarteroni, T.A. Zang,
%                    "Spectral Methods. Fundamentals in Single Domains"
%                    Springer Verlag, Berlin Heidelberg New York, 2006.
%   Written by Paola Gervasio
%   $Date: 2007/04/01$
nov(1:npdx,1)=(1:npdx)';
k=npdx(1);
for ie=2:ne
k1=npdx-1;
nov(1:npdx,ie)=(k:k+k1)'; k=k+k1;
end